import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import posts from '../data/posts.json'
import { useWeb3 } from "@3rdweb/hooks" 
import { contractAddress } from '../config.js'
import { ethers } from 'ethers'
import axios from 'axios'

import DGN from '../utils/DegenSocial.json'

export default function Home() {
  
  const { connectWallet, address, error } = useWeb3();
  
  const post_list = posts.map(post => ({
    // return an object with params.color set to the color's name
    params: { post: post.name,
              post: post.content }
  }))

/*
  	// Checks if wallet is connected
	const checkIfWalletIsConnected = async () => {
		const { ethereum } = window
		if (ethereum) {
			console.log('Got the ethereum obejct: ', ethereum)
		} else {
			console.log('No Wallet found. Connect Wallet')
		}

		const accounts = await ethereum.request({ method: 'eth_accounts' })

		if (accounts.length !== 0) {
			console.log('Found authorized Account: ', accounts[0])
			setCurrentAccount(accounts[0])
		} else {
			console.log('No authorized account found')
		}
	}

  	// Checks if wallet is connected to the correct network
	const checkCorrectNetwork = async () => {
		const { ethereum } = window
		let chainId = await ethereum.request({ method: 'eth_chainId' })
		console.log('Connected to chain:' + chainId)

		const mumbaiChainId = '0x13881'

		if (chainId !== mumbaiChainId) {
			setCorrectNetwork(false)
		} else {
			setCorrectNetwork(true)
		}
	}
*/

	// Creates transaction to mint NFT on clicking Mint Character button
	const sendPost = async () => {
		try {
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      const signer = provider.getSigner();
      const contract = new ethers.Contract(contractAddress, DGN.abi, signer)
      contract.createPost("Bob", "Hello world")
      console.log(signer)
      console.log("called it")
		} 
		 catch (error) {
			console.log('Error Posting', error)
		}
	}

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Degen Social
        </h1>

        <p className={styles.description}>
          The social media platform for sharing and benefitting from your alpha
        </p>

        <button className="px-4 py-2 rounded-md bg-purple-600 cursor-pointer hover:bg-purple-500 text-xl font-semibold duration-100 text-white"
          onClick={()=>connectWallet("injected")}
        >
          Connect Wallet
        </button>

        <div className={styles.card}>
        {posts.map(post => (
          <h2>{post.name}: {post.content}</h2>
        ))}
        </div>

        <form>
        <label for="post">Post your alpha here:</label>
        <input id="post" type="text" />
        
        </form>
        <button type="submit" onClick={sendPost}>Submit Post </button>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
